baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'ANIMANIA'
theme = 'ananke'
DefaultContentLanguage = "en"


SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "ANIMANIA"
    weight = 1
    contentDir = "content/"
    

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "gold"
  author = "Shaswat"
  favicon = "favicon.jpeg"
  site_logo = "logo.png"
  description = "itsg here"
  background_color_class = "bg-navy"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/animania_india?igshid=MzRlODBiNWFlZA=="
